---
deployment:
  tasks:
    - export DEPLOYPATH=/home/apiamic1/public_html/
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
